backend:
  name: github
  repo: kris-lisik/coaching-site
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Блог постове"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заглавие", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Снимка", name: "image", widget: "image" }
      - { label: "Съдържание", name: "body", widget: "markdown" }
